
version: 1.2
workflows:
  - subclass: WDL 
    primaryDescriptorPath: /workflows/prepare_eQTL.wdl
    name: prepare_eQTL
  - subclass: WDL 
    primaryDescriptorPath: /workflows/prepare_pQTL.wdl
    name: prepare_pQTL
  - subclass: WDL
    primaryDescriptorPath: /workflows/normalize_pQTL.wdl
    name: normalize_pQTL
  - subclass: WDL 
    primaryDescriptorPath: /workflows/prepare_sQTL.wdl
    name: prepare_sQTL
  - subclass: WDL
    primaryDescriptorPath: /workflows/merge_methylation.wdl
    name: merge_methylation
  - subclass: WDL
    primaryDescriptorPath: /workflows/ProcessMethylationSample.wdl
    name: process_methylation_sample
  - subclass: WDL
    primaryDescriptorPath: /workflows/AggregateMethylationCohort.wdl
    name: aggregate_methylation_cohort
  - subclass: WDL 
    primaryDescriptorPath: /workflows/calculate_phenotypePCs.wdl
    name: calculate_phenotypePCs
  - subclass: WDL 
    primaryDescriptorPath: /workflows/prepare_VCF.wdl
    name: prepare_VCF
  - subclass: WDL 
    primaryDescriptorPath: /workflows/calculateGenotypePCs.wdl
    name: calculateGenotypePCs
  - subclass: WDL 
    primaryDescriptorPath: /workflows/convertVCF2Plink.wdl    
    name: convertVCF2plink
  - subclass: WDL 
    primaryDescriptorPath: /workflows/MergeCovariates.wdl    
    name: MergeCovariates 
  - subclass: WDL 
    primaryDescriptorPath: /workflows/calculateGenotypeDosage.wdl    
    name: calculateGenotypeDosage
  - subclass: WDL 
    primaryDescriptorPath: /workflows/calculateAF.wdl    
    name: calculateAF 
