testthat::test_that("custom mappings preserve mass and require complete coverage", {
  m <- tibble::tibble(source = c("a", "b", "c"), target = c("CD4 T cells", "B cells", "B cells"))
  p <- matrix(c(.2,.3,.5), 1, dimnames = list("donor", m$source))
  result <- process_proportions(p, cell_type_mapping = m)
  testthat::expect_equal(unname(result$combined), matrix(c(.2,.8),1))
  testthat::expect_error(process_proportions(p, cell_type_mapping = m[1:2,]), "exactly match")
  testthat::expect_error(process_proportions(p*2, cell_type_mapping = m), "sum to one")
  z <- matrix(1:9,3,dimnames=list(c('G1','G2','G3'),m$source))
  testthat::expect_silent(validate_lm22(z,m))
  testthat::expect_error(validate_lm22(z), "22 standard LM22")
})
testthat::test_that("mapping file validation rejects ambiguous and unlocalized inputs", {
  testthat::expect_error(read_cell_type_mapping("gs://bucket/map.tsv"), "localization")
  p <- tempfile(fileext='.tsv')
  readr::write_tsv(tibble::tibble(source=c('a','a'),target=c('x','y')),p)
  testthat::expect_error(read_cell_type_mapping(p), "unique sources")
  readr::write_tsv(tibble::tibble(source=c('a','b'),target=c('x','y')),p)
  testthat::expect_equal(read_cell_type_mapping(p)$target,c('x','y'))
})
