args <- commandArgs(trailingOnly = TRUE)
stopifnot(length(args) == 12L)
opts <- setNames(args[seq(2,12,2)], args[seq(1,11,2)])
.libPaths(c(opts[['--library']], .libPaths()))
suppressPackageStartupMessages({library(readr);library(dplyr);library(SingleCellExperiment);library(scDblFinder)})
message('Loading capture: ', opts[['--capture-dir']])
cells <- read_tsv(file.path(opts[['--capture-dir']], 'cells.tsv'), show_col_types = FALSE)
features <- read_tsv(file.path(opts[['--capture-dir']], 'features.tsv'), show_col_types = FALSE)
counts <- as(Matrix::readMM(gzfile(file.path(opts[['--capture-dir']], 'counts.mtx.gz'))), 'CsparseMatrix')
stopifnot(ncol(counts) == nrow(cells), nrow(counts) == nrow(features), !anyDuplicated(cells$cell_id))
rownames(counts) <- features$feature_id
colnames(counts) <- cells$cell_id
sce <- SingleCellExperiment(assays = list(counts = counts))
seed <- as.integer(opts[['--seed']])
set.seed(seed)
message('Starting scDblFinder ', packageVersion('scDblFinder'), '; cells: ', ncol(sce), '; seed: ', seed)
sce <- scDblFinder(sce, clusters = FALSE, BPPARAM = BiocParallel::SerialParam(RNGseed = seed))
stopifnot(identical(colnames(sce), cells$cell_id))
calls <- bind_cols(cells, as_tibble(as.data.frame(colData(sce))))
stopifnot(all(calls$scDblFinder.class %in% c('singlet', 'doublet')))
write_tsv(calls, opts[['--output']])
writeLines(capture.output(sessionInfo()), opts[['--session-info']])
saveRDS(list(metadata = metadata(sce), seed = seed, package_version = as.character(packageVersion('scDblFinder')), formals = formals(scDblFinder)), opts[['--metadata']])
message('Capture finished; predicted doublets: ', sum(calls$scDblFinder.class == 'doublet'))
